import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import BottomTabBar from '@/component/general/BottomTabBar';
import Navbar from '@/component/general/Navbar';
import { SearchProvider } from './search/components/searchContext';
import { CommentProvider } from './@commentModal/add-comment/commentContext';
import { OrderProvider } from './product/[productId]/components/orderContext';
import { cookies } from 'next/headers';
import { getOrders, getUser } from '@/lib/api';
import MobileBackNav from '@/component/general/MobileBackNav';
import FaNumberProvider from '@/component/general/FaNamberProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  other: {
    'google-site-verification':
      'YGvfmPjp3sRVEVV11-gadtZWDP0fUKs0NekXyPsfOt0'
  }
};

export default async function RootLayout({
  children,
  searched,
  storyModal,
  commentModal
}: Readonly<{
  children: React.ReactNode;
  searched: React.ReactNode;
  storyModal: React.ReactNode;
  commentModal: React.ReactNode;
}>) {
  const token = (await cookies()).get('access_token')
    ?.value as string;
  const user = token && (await getUser(token));
  const currents = token && (await getOrders());

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-md:mb-[200px]`}>
        <FaNumberProvider>
          <OrderProvider
            token={token}
            currents={currents}
            user={user}>
            <CommentProvider>
              <SearchProvider>
                <MobileBackNav />
                <Navbar />
                {children}
                {storyModal}
                {commentModal}
                {searched}
                <BottomTabBar />
              </SearchProvider>
            </CommentProvider>
          </OrderProvider>
        </FaNumberProvider>
      </body>
    </html>
  );
}
